
export class AlertaAnalisis{
    constructor(
        public anaFhAtiende?: string,
		public idAnalisis?: number,
		public idAlerta?: number,
		public fhAlerta?: Date,
		public idDireccion?: number,
		public idReporte?: number,
		public tipoRelacion?: number,
		public idPersonaAnalisis?: number,
		public motivoAlerta?: number,
		public descripcionCaso?: string,
		public idEmpresa?: number,
		public fhIni?: Date,
		public fhFin?: Date,
		public fhCreacionCaso?: Date,
		public usrOwner?: string,
		public usrAsigned?: string,
		public status?: string,
		public anaDomicilio?: number,
		public anaCuestionario?: number,
		public anaTransaccionalidad?: number,
		public anaInfoInternet?: number,	
		public folioReporte?: string,
		public reglaAlerta?: number,
		public resVisita?: number,
		public entrevistaTel?: number,
		public soporteDocumental?: number,
		public soporteDocumentalOtro?: string,
		public causaComite?: number,
		public tipoAlerta?: number,	
		public repTipoReporte?: number,
		public repModalidadReporte?: number,
		public anaContrato?: number,
		public anaRevDomicilioOtro?: string,
		public anaRevCuestionarioOtro?: string,
		public anaRevTransaccionalidadOtro?: string,
		public anaRevInfoInternetOtro?: string,
		public anaCausaComiteOtro?: string,
		public anaPrioridad?: number,	
		public stsClave?: string,
		public anaManual?: Boolean,
		public anaEmploy?: number,
		public caAlertaGrupo?: number,
		public anaAutoridad?: number,
		public anaFhComite?: Date,
		public anaComentarioG?: string,
		public nomCortoPersona?: string,
		public anaTipoPersona?: string,
		public escenarioDesc?: string,
		public reglaDesc?: string,
		public empresaDesc?: string,
		public statusStr?: string,
		public longitudCampo40?: number,
		public longitudCampo41?: number,		
		public repTipoReporteStr?: string,
		public repModalidadReporteStr?: string,
		public esTentativa?: Boolean,
		public reglaRotaDesc?: any,
		public dias?: string,
		public nomUsuCom?: any,
		
		public diasCarga?: number,
		public diasAtencion?: number,
		public stsClaveStr?: string,
		public prioridadStr?: string,
		public selectCasoJust: Boolean=false,
		public selectCasoDene: Boolean=false,
		public comentarioGerente?: string,
		private _fhComite?: Date,
		public selectCaso: Boolean=false,
		
		public selectCasoAnioDia: Boolean=false,
		
		public anaJustifica: Boolean=false,
		
		public idAnalisisSybase?: number,

		public montoOperacionSybase?: string,
		public fechaOperacionSybase?: Date,
		public descOperacionSybase?: string,
		public folioOperacionSybase?: string,

		public anaTipoReporte?: number,
		public anaNumeroOficio?: string,
		public anaNumeroAcuerdo?: string,
		public anaFhSaldoAsegurado?: Date,
		public anaFhNumeroOficio?: Date,
		public anaLpbRelacionado?: number,
		
		public anaFhListaNegra?: Date,
		public anaListaNegra?: string,
		
		public anaVotacionContinuidad?: any,
		public anaVotacionReporte?: any
    ){}
}