export class InstruccionTransferenciaVO {
  constructor(
    public conId?: number,
    public instId?: number,
    public fechaValor?: Date,
    public monto?: number,
    public divisa?: string,
    public instRefMedio1?: string,
    public ciudadDescripcion?: string,
    public branchDescripcion?: string,
    public claveSwiftAba?: string,
    public iban?: string,
    public codigoBanco?: string,
    public codigoBranch?: string,
    public cuentaCliente?: string,
    public digito?: string,
    public beneficiarioInformacion?: string,
    public ordenante?: string,
    public swiftIntermedario?: string,
    public abaIntermediario?: string,
    public cuentaIntermediario?: string,
    public paisIntermediario?: string,
    public ciudadIntermediario?: string,
    public pais?: string,
    public beneficiario?: string,
    public instCuentaNostro?: string,
    public cueId?: number,
    public tipoCargo?: string,
    public medioOrigen?: number,
    public paisBeneficiario?: string,
    public domicilioBeneficiario?: string,
    public conceptoPago?: string
  ) {}
}
