import { ContratoVO } from "@intercam/model";

export class TransferLiquidacionVO {
  constructor(
      public instId?: number, 
      public instFoper?: Date, 
      public tipCveLiq?: string,
      public divId?: string, 
      public cueId?: number, 
      public instMonto?: number,
      public conId?: number, 
      public concId?: number, 
      public banId?: number, 
      public instSucLiq?: number, 
      public instBeneficiario?: string, 
      public instIdLeyendaCheque?: number, 
      public instRefMedio1?: string, 
      public instRefMedio2?: string, 
      public medId?: number, 
      public instBancoClienteId?: number, 
      public instPlazaBcoCliente?: string, 
      public instSucBcoCliente?: string, 
      public cveTipoCta?: string, 
      public instStatus?: string, 
      public instDescDomicilio?: string, 
      public instComentario?: string, 
      public instPersonaRecibe?: string, 
      public instConvenio?: string, 
      public instRefPago?: string, 
      public instInfBcoPagador?: string, 
      public instLocBcoPagador?: string, 
      public instInfOrdenante?: string, 
      public instCveBcoPagador?: string, 
      public instCveBcoInterm?: string, 
      public instCvePais?: string, 
      public instLocBcoInterm?: string, 
      public instFhRegistro?: Date, 
      public instFhUltimoStatus?: Date, 
      public instBreferenciado?: string, 
      public instInfBeneficiario?: string, 
      public instTipoPagoInterm?: string, 
      public instTipoPagoPagador?: string, 
      public instInfBcoInterm?: string, 
      public instCvePaisInterm?: string, 
      public instTipCargoTrf?: string, 
      public instCtaClabeCliente?: string, 
      public instPagoSpeiId?: string, 
      public instTipoOpeSpei?: number, 
      public instTopologiaSpei?: string, 
      public instTipoSiacSpei?: string, 
      public medClave?: string, 
      public insClave?: string, 
      public atrClave?: string, 
      public plaId?: string, 
      public instNumCheque?: number, 
      public bRevisadaPld?: string, 
      public cveOpe?: string, 
      public usuClave?: number, 
      public instCuentaNostro?: string, 
      public instCueIdCliente?: number, 
      public instCuentaCliente?: string, 
      public instIdRel?: number, 
      public paiClave?: number, 
      public instFormatoId?: number, 
      public instReglaPerId?: number, 
      public instTipoPagoSpei?: number, 
      public instTipoCuentaSpei?: number, 
      public instPrioridadSpei?: number, 
      public instFormaAutoriza?: string, 
      public ordenId?: number, 
      public instBnkCod?: string, 
      public instBrcCof?: string, 
      public instCuentaInterm?: string,
      public contrato?:ContratoVO,
      public medioOrigenDesc?:string,
      public instAbaInterm?: string,
      public cuentaSwift?:string,
      public conSelected?:boolean,
    ) {}
}